import {NODES,DEFAULTS,START,PARAMETERS,numericValue,TOTAL_ORDERS} from './engine.js';
import {flow,diagnose,RECOVERY} from './flow.js';
const $=id=>document.getElementById(id),STORE='supply-lab-v4';
let decisions={...START,values:{}},recovery={},active=0,phase='plan';
const fmt=n=>Math.round(n).toLocaleString('es-CL');
function el(tag,cls,txt){const e=document.createElement(tag);if(cls)e.className=cls;if(txt!==undefined)e.textContent=txt;return e}
function add(parent,tag,cls,txt){const e=el(tag,cls,txt);parent.append(e);return e}
function save(){try{localStorage.setItem(STORE,JSON.stringify({decisions,recovery,active,phase}))}catch{}}
function load(){try{const v=JSON.parse(localStorage.getItem(STORE)||'null');if(!v)return;for(const n of NODES){if(n.choices.some(c=>c.id===v.decisions?.[n.id]))decisions[n.id]=v.decisions[n.id];const raw=v.decisions?.values?.[n.id],p=PARAMETERS[n.id];if(raw!==undefined&&Number.isFinite(Number(raw))&&Number(raw)>=p.min&&Number(raw)<=p.max)decisions.values[n.id]=Number(raw);if(RECOVERY[n.id]?.some(a=>a.id===v.recovery?.[n.id]))recovery[n.id]=v.recovery[n.id]}active=Number.isInteger(v.active)?Math.max(0,Math.min(7,v.active)):0;phase=v.phase==='recover'?'recover':'plan'}catch{}}
function nav(i){active=i;save();render();$('mission').scrollIntoView({behavior:'smooth',block:'start'})}
function map(){const root=$('roadmap');root.replaceChildren();NODES.forEach((n,i)=>{const b=add(root,'button','node '+(active===i?'current':decisions[n.id]?'done':''));b.type='button';b.setAttribute('aria-current',active===i?'step':'false');add(b,'span','node-icon',n.icon);const c=add(b,'span','node-content');add(c,'strong','',String(i+1).padStart(2,'0')+' · '+n.title);add(c,'small','',recovery[n.id]?'Medida de recuperación aplicada':decisions[n.id]?'Planificación registrada':'Pendiente de planificar');add(b,'span','node-state',active===i?'●':decisions[n.id]?'✓':'→');b.addEventListener('click',()=>nav(i))});const done=NODES.filter(n=>decisions[n.id]).length;$('progressText').textContent=done+' de 8 áreas planificadas · '+(phase==='plan'?'Fase 1: planificar':'Fase 2: recuperar');$('progressFill').style.width=done/8*100+'%'}
function choiceButtons(n,root){const selected=decisions[n.id]??DEFAULTS[n.id];n.choices.forEach(c=>{const b=add(root,'button','choice '+(selected===c.id?'selected':''));b.type='button';b.setAttribute('aria-pressed',String(selected===c.id));add(b,'strong','',c.label);add(b,'small','',c.note);b.addEventListener('click',()=>{decisions[n.id]=c.id;decisions.values[n.id]=c[PARAMETERS[n.id].key];save();render()})})}
function numeric(n,root){const p=PARAMETERS[n.id],control=add(root,'div','numeric-control');add(control,'label','',p.label+' ('+p.unit.trim()+')');add(control,'p','muted',p.hint);const row=add(control,'div','numeric-row'),input=add(row,'input','numeric-input'),range=add(row,'input','numeric-range');for(const field of [input,range]){field.type=field===input?'number':'range';field.min=p.min;field.max=p.max;field.step=p.step;field.value=numericValue(n.id,decisions);field.setAttribute('aria-label',p.label)}const err=add(control,'div','input-error');err.setAttribute('role','status');const update=value=>{const x=Number(value);if(value===''||!Number.isFinite(x)||x<p.min||x>p.max){err.textContent='Ingresa un valor entre '+p.min+' y '+p.max;return}decisions[n.id]=decisions[n.id]??DEFAULTS[n.id];decisions.values[n.id]=x;save();render()};input.addEventListener('change',()=>update(input.value));range.addEventListener('change',()=>update(range.value))}
function mission(r){const n=NODES[active],stage=r.stages[active];$('missionNumber').textContent=(phase==='plan'?'PLANIFICACIÓN':'RECUPERACIÓN')+' · '+String(active+1).padStart(2,'0')+' / 08';$('missionTitle').textContent=n.icon+' '+n.title;$('missionDescription').textContent=n.desc;$('missionKpi').textContent=n.kpi;const root=$('choices');root.replaceChildren();add(root,'h3','','1 · Define la operación');choiceButtons(n,root);numeric(n,root);
const flowBox=add(root,'div','flow-summary');add(flowBox,'strong','','Resultado real en cadena');add(flowBox,'p','','Recibe '+fmt(stage.incoming)+' '+stage.unit+' · Procesa '+fmt(stage.processed)+' '+stage.unit+' · Capacidad '+fmt(stage.capacity)+' '+stage.unit+'.');add(flowBox,'small','',stage.reason);
if(phase==='recover'){add(root,'h3','','2 · Decide cómo recuperar');const opts=RECOVERY[n.id]||[];for(const opt of opts){const b=add(root,'button','choice '+(recovery[n.id]===opt.id?'selected':''));add(b,'strong','',opt.label);add(b,'small','',opt.note);const potential=flow(decisions,{...recovery,[n.id]:opt.id}).dispatched-r.dispatched;add(b,'small','',potential>0?'Impacto aislado estimado: +'+fmt(potential)+' pedidos':'Sin recuperación inmediata de pedidos; puede ayudar a otro cuello de botella.');b.addEventListener('click',()=>{if(recovery[n.id]===opt.id)delete recovery[n.id];else recovery[n.id]=opt.id;save();render()})}}
$('nodeResult').textContent='Con las decisiones actuales, '+fmt(r.dispatched)+' pedidos pueden completar toda la cadena. '+(stage.processed<stage.incoming?'Esta área recibe más carga de la que puede procesar o liberar.':'Esta área no reduce su flujo de entrada en esta etapa.');$('prev').disabled=active===0;$('next').textContent=active===7?(phase==='plan'?'Iniciar recuperación →':'Ver diagnóstico →'):'Siguiente área →'}
function results(r){$('completed').textContent=fmt(r.dispatched);$('pending').textContent=fmt(r.pending);$('fulfillment').textContent=(r.dispatched/TOTAL_ORDERS*100).toFixed(1).replace('.',',')+'%';$('forecastNotice').textContent=phase==='plan'?'Proyección provisional: los nodos no planificados usan parámetros estándar. La operación se propaga por SKU.':'Fase de recuperación: cada medida actualiza toda la cadena y sus restricciones.';const bottleneck=r.limiting.map(id=>NODES.find(n=>n.id===id)?.title).join(', ');$('cause').textContent='Restricción final: '+(bottleneck||'sin restricciones')+'. Transporte recibe '+fmt(r.picked)+' pedidos preparados y solo puede expedir '+fmt(r.dispatched)+'. Capacidad máxima propia: '+fmt(r.metrics.transport)+'.';
const sku=$('sku');sku.replaceChildren();r.product.forEach(p=>{const row=add(sku,'div','sku-row');add(row,'strong','',p.name);add(row,'span','','Necesidad '+fmt(p.target)+' · Disponible '+fmt(p.usable));const track=add(row,'div','sku-track');const fill=add(track,'div','sku-fill');fill.style.width=Math.min(100,p.usable/p.target*100)+'%';add(row,'small','','Compra '+fmt(p.ordered)+' → llega '+fmt(p.delivered)+' → recibe '+fmt(p.received)+' → libera '+fmt(p.approved)+' · reserva +'+fmt(p.reserveUsed))});
const list=$('results');list.replaceChildren();r.stages.forEach(s=>{const n=NODES.find(n=>n.id===s.id),line=add(list,'div','stage-result');add(line,'span','',n.icon+' '+n.title);add(line,'strong','',fmt(s.processed)+' '+s.unit);add(line,'small','','Entrada '+fmt(s.incoming)+' · Capacidad '+fmt(s.capacity)+' · '+s.reason)});
const d=diagnose(decisions,recovery),causes=$('rootCauses');causes.replaceChildren();for(const c of d.findings){const row=add(causes,'div','action');add(row,'span','action-index',c.icon);const content=add(row,'div','');add(content,'strong','',c.title+(c.selected?' · medida aplicada':''));add(content,'small','','Diferencia vs referencia: '+(c.referenceDelta>=0?'+':'')+fmt(c.referenceDelta)+' pedidos · Mejora correctiva individual posible: +'+fmt(c.improvement)+'.');}
const actions=$('actions');actions.replaceChildren();if(!d.priority.length)add(actions,'p','muted','No se detectaron medidas individuales que mejoren pedidos completables. Revisa restricciones combinadas.');d.priority.forEach(c=>{if(!c.action)return;const row=add(actions,'div','action');add(row,'span','action-index',c.icon);const body=add(row,'div','');add(body,'strong','',c.title+' · '+c.action.label);add(body,'small','','Recuperación estimada: +'+fmt(c.improvement)+' pedidos, manteniendo el resto constante.');const b=add(row,'button','mini','Aplicar');b.addEventListener('click',()=>{recovery[c.id]=c.action.id;save();render()})});$('riskCount').textContent=String(r.limiting.length);$('focus').textContent=bottleneck||'Sin restricciones';$('report').hidden=phase!=='recover'}
function render(){const r=flow(decisions,recovery);map();mission(r);results(r)}
$('prev').addEventListener('click',()=>nav(Math.max(0,active-1)));
$('next').addEventListener('click',()=>{const n=NODES[active];if(!decisions[n.id])decisions[n.id]=DEFAULTS[n.id];if(active<7)active++;else if(phase==='plan'){phase='recover';active=0}else{$('report').hidden=false;save();render();$('report').scrollIntoView({behavior:'smooth',block:'start'});return}save();render();$('mission').scrollIntoView({behavior:'smooth',block:'start'})});
$('reset').addEventListener('click',()=>{if(!confirm('¿Reiniciar planificación y recuperación de la campaña?'))return;decisions={...START,values:{}};recovery={};active=0;phase='plan';save();render()});
$('openReport').addEventListener('click',()=>{phase='recover';save();render();$('report').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const r=flow(decisions,recovery),rows=[['Área','Entrada','Procesado','Capacidad','Unidad','Acción correctiva'],...r.stages.map(s=>[NODES.find(n=>n.id===s.id).title,s.incoming,s.processed,s.capacity,s.unit,recovery[s.id]||''])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download='supply-chain-flujo-recuperacion.csv';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)});
load();render();
